// Generated by gencxx from file db_chassis/DodobotOdomReset.msg
// DO NOT EDIT!


#pragma once

#include <miniros/traits/service_traits.h>


#include <db_chassis/DodobotOdomResetRequest.hxx>
#include <db_chassis/DodobotOdomResetResponse.hxx>


namespace db_chassis
{

struct DodobotOdomReset
{

typedef DodobotOdomResetRequest Request;
typedef DodobotOdomResetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DodobotOdomReset
} // namespace db_chassis


namespace miniros
{
namespace service_traits
{


template<>
struct MD5Sum< ::db_chassis::DodobotOdomReset > {
  static const char* value()
  {
    return "e3e4a3dc1c93d6b6068349e9ef1ffdd6";
  }

  static const char* value(const ::db_chassis::DodobotOdomReset&) { return value(); }
};

template<>
struct DataType< ::db_chassis::DodobotOdomReset > {
  static const char* value()
  {
    return "db_chassis/DodobotOdomReset";
  }

  static const char* value(const ::db_chassis::DodobotOdomReset&) { return value(); }
};


// service_traits::MD5Sum< ::db_chassis::DodobotOdomResetRequest> should match 
// service_traits::MD5Sum< ::db_chassis::DodobotOdomReset > 
template<>
struct MD5Sum< ::db_chassis::DodobotOdomResetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::db_chassis::DodobotOdomReset >::value();
  }
  static const char* value(const ::db_chassis::DodobotOdomResetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::db_chassis::DodobotOdomResetRequest> should match 
// service_traits::DataType< ::db_chassis::DodobotOdomReset > 
template<>
struct DataType< ::db_chassis::DodobotOdomResetRequest>
{
  static const char* value()
  {
    return DataType< ::db_chassis::DodobotOdomReset >::value();
  }
  static const char* value(const ::db_chassis::DodobotOdomResetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::db_chassis::DodobotOdomResetResponse> should match 
// service_traits::MD5Sum< ::db_chassis::DodobotOdomReset > 
template<>
struct MD5Sum< ::db_chassis::DodobotOdomResetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::db_chassis::DodobotOdomReset >::value();
  }
  static const char* value(const ::db_chassis::DodobotOdomResetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::db_chassis::DodobotOdomResetResponse> should match 
// service_traits::DataType< ::db_chassis::DodobotOdomReset > 
template<>
struct DataType< ::db_chassis::DodobotOdomResetResponse>
{
  static const char* value()
  {
    return DataType< ::db_chassis::DodobotOdomReset >::value();
  }
  static const char* value(const ::db_chassis::DodobotOdomResetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace miniros
