// Generated by gencxx from file db_audio/PlayAudio.msg
// DO NOT EDIT!


#pragma once

#include <miniros/traits/service_traits.h>


#include <db_audio/PlayAudioRequest.hxx>
#include <db_audio/PlayAudioResponse.hxx>


namespace db_audio
{

struct PlayAudio
{

typedef PlayAudioRequest Request;
typedef PlayAudioResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PlayAudio
} // namespace db_audio


namespace miniros
{
namespace service_traits
{


template<>
struct MD5Sum< ::db_audio::PlayAudio > {
  static const char* value()
  {
    return "33d79a3b531eddd03799bf2998e16b4d";
  }

  static const char* value(const ::db_audio::PlayAudio&) { return value(); }
};

template<>
struct DataType< ::db_audio::PlayAudio > {
  static const char* value()
  {
    return "db_audio/PlayAudio";
  }

  static const char* value(const ::db_audio::PlayAudio&) { return value(); }
};


// service_traits::MD5Sum< ::db_audio::PlayAudioRequest> should match 
// service_traits::MD5Sum< ::db_audio::PlayAudio > 
template<>
struct MD5Sum< ::db_audio::PlayAudioRequest>
{
  static const char* value()
  {
    return MD5Sum< ::db_audio::PlayAudio >::value();
  }
  static const char* value(const ::db_audio::PlayAudioRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::db_audio::PlayAudioRequest> should match 
// service_traits::DataType< ::db_audio::PlayAudio > 
template<>
struct DataType< ::db_audio::PlayAudioRequest>
{
  static const char* value()
  {
    return DataType< ::db_audio::PlayAudio >::value();
  }
  static const char* value(const ::db_audio::PlayAudioRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::db_audio::PlayAudioResponse> should match 
// service_traits::MD5Sum< ::db_audio::PlayAudio > 
template<>
struct MD5Sum< ::db_audio::PlayAudioResponse>
{
  static const char* value()
  {
    return MD5Sum< ::db_audio::PlayAudio >::value();
  }
  static const char* value(const ::db_audio::PlayAudioResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::db_audio::PlayAudioResponse> should match 
// service_traits::DataType< ::db_audio::PlayAudio > 
template<>
struct DataType< ::db_audio::PlayAudioResponse>
{
  static const char* value()
  {
    return DataType< ::db_audio::PlayAudio >::value();
  }
  static const char* value(const ::db_audio::PlayAudioResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace miniros
