// Generated by gencxx from file db_audio/StopAudio.msg
// DO NOT EDIT!


#pragma once

#include <miniros/traits/service_traits.h>


#include <db_audio/StopAudioRequest.hxx>
#include <db_audio/StopAudioResponse.hxx>


namespace db_audio
{

struct StopAudio
{

typedef StopAudioRequest Request;
typedef StopAudioResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StopAudio
} // namespace db_audio


namespace miniros
{
namespace service_traits
{


template<>
struct MD5Sum< ::db_audio::StopAudio > {
  static const char* value()
  {
    return "33d79a3b531eddd03799bf2998e16b4d";
  }

  static const char* value(const ::db_audio::StopAudio&) { return value(); }
};

template<>
struct DataType< ::db_audio::StopAudio > {
  static const char* value()
  {
    return "db_audio/StopAudio";
  }

  static const char* value(const ::db_audio::StopAudio&) { return value(); }
};


// service_traits::MD5Sum< ::db_audio::StopAudioRequest> should match 
// service_traits::MD5Sum< ::db_audio::StopAudio > 
template<>
struct MD5Sum< ::db_audio::StopAudioRequest>
{
  static const char* value()
  {
    return MD5Sum< ::db_audio::StopAudio >::value();
  }
  static const char* value(const ::db_audio::StopAudioRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::db_audio::StopAudioRequest> should match 
// service_traits::DataType< ::db_audio::StopAudio > 
template<>
struct DataType< ::db_audio::StopAudioRequest>
{
  static const char* value()
  {
    return DataType< ::db_audio::StopAudio >::value();
  }
  static const char* value(const ::db_audio::StopAudioRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::db_audio::StopAudioResponse> should match 
// service_traits::MD5Sum< ::db_audio::StopAudio > 
template<>
struct MD5Sum< ::db_audio::StopAudioResponse>
{
  static const char* value()
  {
    return MD5Sum< ::db_audio::StopAudio >::value();
  }
  static const char* value(const ::db_audio::StopAudioResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::db_audio::StopAudioResponse> should match 
// service_traits::DataType< ::db_audio::StopAudio > 
template<>
struct DataType< ::db_audio::StopAudioResponse>
{
  static const char* value()
  {
    return DataType< ::db_audio::StopAudio >::value();
  }
  static const char* value(const ::db_audio::StopAudioResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace miniros
