// Generated by gencxx from file db_parsing/DodobotPidSrv.msg
// DO NOT EDIT!


#pragma once

#include <miniros/traits/service_traits.h>


#include <db_parsing/DodobotPidSrvRequest.hxx>
#include <db_parsing/DodobotPidSrvResponse.hxx>


namespace db_parsing
{

struct DodobotPidSrv
{

typedef DodobotPidSrvRequest Request;
typedef DodobotPidSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DodobotPidSrv
} // namespace db_parsing


namespace miniros
{
namespace service_traits
{


template<>
struct MD5Sum< ::db_parsing::DodobotPidSrv > {
  static const char* value()
  {
    return "9a670d96deb3eb760af60aaea197996c";
  }

  static const char* value(const ::db_parsing::DodobotPidSrv&) { return value(); }
};

template<>
struct DataType< ::db_parsing::DodobotPidSrv > {
  static const char* value()
  {
    return "db_parsing/DodobotPidSrv";
  }

  static const char* value(const ::db_parsing::DodobotPidSrv&) { return value(); }
};


// service_traits::MD5Sum< ::db_parsing::DodobotPidSrvRequest> should match 
// service_traits::MD5Sum< ::db_parsing::DodobotPidSrv > 
template<>
struct MD5Sum< ::db_parsing::DodobotPidSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::db_parsing::DodobotPidSrv >::value();
  }
  static const char* value(const ::db_parsing::DodobotPidSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::db_parsing::DodobotPidSrvRequest> should match 
// service_traits::DataType< ::db_parsing::DodobotPidSrv > 
template<>
struct DataType< ::db_parsing::DodobotPidSrvRequest>
{
  static const char* value()
  {
    return DataType< ::db_parsing::DodobotPidSrv >::value();
  }
  static const char* value(const ::db_parsing::DodobotPidSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::db_parsing::DodobotPidSrvResponse> should match 
// service_traits::MD5Sum< ::db_parsing::DodobotPidSrv > 
template<>
struct MD5Sum< ::db_parsing::DodobotPidSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::db_parsing::DodobotPidSrv >::value();
  }
  static const char* value(const ::db_parsing::DodobotPidSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::db_parsing::DodobotPidSrvResponse> should match 
// service_traits::DataType< ::db_parsing::DodobotPidSrv > 
template<>
struct DataType< ::db_parsing::DodobotPidSrvResponse>
{
  static const char* value()
  {
    return DataType< ::db_parsing::DodobotPidSrv >::value();
  }
  static const char* value(const ::db_parsing::DodobotPidSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace miniros
