// Generated by gencxx from file db_parsing/DodobotUploadFile.msg
// DO NOT EDIT!


#pragma once

#include <miniros/traits/service_traits.h>


#include <db_parsing/DodobotUploadFileRequest.hxx>
#include <db_parsing/DodobotUploadFileResponse.hxx>


namespace db_parsing
{

struct DodobotUploadFile
{

typedef DodobotUploadFileRequest Request;
typedef DodobotUploadFileResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DodobotUploadFile
} // namespace db_parsing


namespace miniros
{
namespace service_traits
{


template<>
struct MD5Sum< ::db_parsing::DodobotUploadFile > {
  static const char* value()
  {
    return "70b33e9f2ecc7d725fb8feb5b3a0b1aa";
  }

  static const char* value(const ::db_parsing::DodobotUploadFile&) { return value(); }
};

template<>
struct DataType< ::db_parsing::DodobotUploadFile > {
  static const char* value()
  {
    return "db_parsing/DodobotUploadFile";
  }

  static const char* value(const ::db_parsing::DodobotUploadFile&) { return value(); }
};


// service_traits::MD5Sum< ::db_parsing::DodobotUploadFileRequest> should match 
// service_traits::MD5Sum< ::db_parsing::DodobotUploadFile > 
template<>
struct MD5Sum< ::db_parsing::DodobotUploadFileRequest>
{
  static const char* value()
  {
    return MD5Sum< ::db_parsing::DodobotUploadFile >::value();
  }
  static const char* value(const ::db_parsing::DodobotUploadFileRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::db_parsing::DodobotUploadFileRequest> should match 
// service_traits::DataType< ::db_parsing::DodobotUploadFile > 
template<>
struct DataType< ::db_parsing::DodobotUploadFileRequest>
{
  static const char* value()
  {
    return DataType< ::db_parsing::DodobotUploadFile >::value();
  }
  static const char* value(const ::db_parsing::DodobotUploadFileRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::db_parsing::DodobotUploadFileResponse> should match 
// service_traits::MD5Sum< ::db_parsing::DodobotUploadFile > 
template<>
struct MD5Sum< ::db_parsing::DodobotUploadFileResponse>
{
  static const char* value()
  {
    return MD5Sum< ::db_parsing::DodobotUploadFile >::value();
  }
  static const char* value(const ::db_parsing::DodobotUploadFileResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::db_parsing::DodobotUploadFileResponse> should match 
// service_traits::DataType< ::db_parsing::DodobotUploadFile > 
template<>
struct DataType< ::db_parsing::DodobotUploadFileResponse>
{
  static const char* value()
  {
    return DataType< ::db_parsing::DodobotUploadFile >::value();
  }
  static const char* value(const ::db_parsing::DodobotUploadFileResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace miniros
