// Generated by gencxx from file db_parsing/DodobotGetState.msg
// DO NOT EDIT!


#pragma once

#include <miniros/traits/service_traits.h>


#include <db_parsing/DodobotGetStateRequest.hxx>
#include <db_parsing/DodobotGetStateResponse.hxx>


namespace db_parsing
{

struct DodobotGetState
{

typedef DodobotGetStateRequest Request;
typedef DodobotGetStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DodobotGetState
} // namespace db_parsing


namespace miniros
{
namespace service_traits
{


template<>
struct MD5Sum< ::db_parsing::DodobotGetState > {
  static const char* value()
  {
    return "4c01d362382e7c93b8d729b6e9ad99c8";
  }

  static const char* value(const ::db_parsing::DodobotGetState&) { return value(); }
};

template<>
struct DataType< ::db_parsing::DodobotGetState > {
  static const char* value()
  {
    return "db_parsing/DodobotGetState";
  }

  static const char* value(const ::db_parsing::DodobotGetState&) { return value(); }
};


// service_traits::MD5Sum< ::db_parsing::DodobotGetStateRequest> should match 
// service_traits::MD5Sum< ::db_parsing::DodobotGetState > 
template<>
struct MD5Sum< ::db_parsing::DodobotGetStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::db_parsing::DodobotGetState >::value();
  }
  static const char* value(const ::db_parsing::DodobotGetStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::db_parsing::DodobotGetStateRequest> should match 
// service_traits::DataType< ::db_parsing::DodobotGetState > 
template<>
struct DataType< ::db_parsing::DodobotGetStateRequest>
{
  static const char* value()
  {
    return DataType< ::db_parsing::DodobotGetState >::value();
  }
  static const char* value(const ::db_parsing::DodobotGetStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::db_parsing::DodobotGetStateResponse> should match 
// service_traits::MD5Sum< ::db_parsing::DodobotGetState > 
template<>
struct MD5Sum< ::db_parsing::DodobotGetStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::db_parsing::DodobotGetState >::value();
  }
  static const char* value(const ::db_parsing::DodobotGetStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::db_parsing::DodobotGetStateResponse> should match 
// service_traits::DataType< ::db_parsing::DodobotGetState > 
template<>
struct DataType< ::db_parsing::DodobotGetStateResponse>
{
  static const char* value()
  {
    return DataType< ::db_parsing::DodobotGetState >::value();
  }
  static const char* value(const ::db_parsing::DodobotGetStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace miniros
