// Generated by gencxx from file db_parsing/DodobotSetState.msg
// DO NOT EDIT!


#pragma once

#include <miniros/traits/service_traits.h>


#include <db_parsing/DodobotSetStateRequest.hxx>
#include <db_parsing/DodobotSetStateResponse.hxx>


namespace db_parsing
{

struct DodobotSetState
{

typedef DodobotSetStateRequest Request;
typedef DodobotSetStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DodobotSetState
} // namespace db_parsing


namespace miniros
{
namespace service_traits
{


template<>
struct MD5Sum< ::db_parsing::DodobotSetState > {
  static const char* value()
  {
    return "9c92e37f29b56a2fd386449d921bfd6b";
  }

  static const char* value(const ::db_parsing::DodobotSetState&) { return value(); }
};

template<>
struct DataType< ::db_parsing::DodobotSetState > {
  static const char* value()
  {
    return "db_parsing/DodobotSetState";
  }

  static const char* value(const ::db_parsing::DodobotSetState&) { return value(); }
};


// service_traits::MD5Sum< ::db_parsing::DodobotSetStateRequest> should match 
// service_traits::MD5Sum< ::db_parsing::DodobotSetState > 
template<>
struct MD5Sum< ::db_parsing::DodobotSetStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::db_parsing::DodobotSetState >::value();
  }
  static const char* value(const ::db_parsing::DodobotSetStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::db_parsing::DodobotSetStateRequest> should match 
// service_traits::DataType< ::db_parsing::DodobotSetState > 
template<>
struct DataType< ::db_parsing::DodobotSetStateRequest>
{
  static const char* value()
  {
    return DataType< ::db_parsing::DodobotSetState >::value();
  }
  static const char* value(const ::db_parsing::DodobotSetStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::db_parsing::DodobotSetStateResponse> should match 
// service_traits::MD5Sum< ::db_parsing::DodobotSetState > 
template<>
struct MD5Sum< ::db_parsing::DodobotSetStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::db_parsing::DodobotSetState >::value();
  }
  static const char* value(const ::db_parsing::DodobotSetStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::db_parsing::DodobotSetStateResponse> should match 
// service_traits::DataType< ::db_parsing::DodobotSetState > 
template<>
struct DataType< ::db_parsing::DodobotSetStateResponse>
{
  static const char* value()
  {
    return DataType< ::db_parsing::DodobotSetState >::value();
  }
  static const char* value(const ::db_parsing::DodobotSetStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace miniros
