// Generated by gencxx from file db_parsing/DodobotListDir.msg
// DO NOT EDIT!


#pragma once

#include <miniros/traits/service_traits.h>


#include <db_parsing/DodobotListDirRequest.hxx>
#include <db_parsing/DodobotListDirResponse.hxx>


namespace db_parsing
{

struct DodobotListDir
{

typedef DodobotListDirRequest Request;
typedef DodobotListDirResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DodobotListDir
} // namespace db_parsing


namespace miniros
{
namespace service_traits
{


template<>
struct MD5Sum< ::db_parsing::DodobotListDir > {
  static const char* value()
  {
    return "61907ff9944eda66eaa9c2f122abc628";
  }

  static const char* value(const ::db_parsing::DodobotListDir&) { return value(); }
};

template<>
struct DataType< ::db_parsing::DodobotListDir > {
  static const char* value()
  {
    return "db_parsing/DodobotListDir";
  }

  static const char* value(const ::db_parsing::DodobotListDir&) { return value(); }
};


// service_traits::MD5Sum< ::db_parsing::DodobotListDirRequest> should match 
// service_traits::MD5Sum< ::db_parsing::DodobotListDir > 
template<>
struct MD5Sum< ::db_parsing::DodobotListDirRequest>
{
  static const char* value()
  {
    return MD5Sum< ::db_parsing::DodobotListDir >::value();
  }
  static const char* value(const ::db_parsing::DodobotListDirRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::db_parsing::DodobotListDirRequest> should match 
// service_traits::DataType< ::db_parsing::DodobotListDir > 
template<>
struct DataType< ::db_parsing::DodobotListDirRequest>
{
  static const char* value()
  {
    return DataType< ::db_parsing::DodobotListDir >::value();
  }
  static const char* value(const ::db_parsing::DodobotListDirRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::db_parsing::DodobotListDirResponse> should match 
// service_traits::MD5Sum< ::db_parsing::DodobotListDir > 
template<>
struct MD5Sum< ::db_parsing::DodobotListDirResponse>
{
  static const char* value()
  {
    return MD5Sum< ::db_parsing::DodobotListDir >::value();
  }
  static const char* value(const ::db_parsing::DodobotListDirResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::db_parsing::DodobotListDirResponse> should match 
// service_traits::DataType< ::db_parsing::DodobotListDir > 
template<>
struct DataType< ::db_parsing::DodobotListDirResponse>
{
  static const char* value()
  {
    return DataType< ::db_parsing::DodobotListDir >::value();
  }
  static const char* value(const ::db_parsing::DodobotListDirResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace miniros
